#!/usr/bin/perl
#
# A scaffold for Wordpress plugins on UBOS.
#
# This file is part of ubos-scaffold.
# (C) 2017 Indie Computing Corp.
#
# ubos-scaffold is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ubos-scaffold is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ubos-scaffold.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use warnings;

package UBOS::Scaffold::Scaffolds::WordpressPlugin;

##
# Declare which parameters should be provided for this scaffold.
sub pars {
    return [
        {
            'name'        => 'name',
            'description' => <<DESC
Name of the Wordpress plugin
DESC
        },
        {
            'name'        => 'developer',
            'description' => <<DESC
URL of the developer, such as your company URL
DESC
        },
        {
            'name'        => 'url',
            'description' => <<DESC
URL of the package, such as a product information page on your company website
DESC
        },
        {
            'name'        => 'description',
            'description' => <<DESC
One-line description of your package, which will be shown to the user when
they ask pacman about your package (-i flag to pacman)
DESC
        }
    ];
}

##
# Do the generation
# $pars: the parameters to use
# $dir: the output directory
sub generate {
    my $pars = shift;
    my $dir  = shift;

    my $pkgBuild = <<END;
#
# PKGBUILD for package $pars->{name}, generated by ubos-scaffold.
# For the syntax of this file, please refer to the description on the
# Arch Linux wiki here: https://wiki.archlinux.org/index.php/PKGBUILD
#

developer="$pars->{developer}"
url="$pars->{url}"
maintainer=\${developer}
pkgname=wordpress-plugin-$pars->{name}
pkgver=0.1
pkgrel=1
pkgdesc="$pars->{description}"
arch=('any')
license=GPL
depends=(
    # Insert your UBOS package dependencies here as a bash array, like this:
    #     'wordpress'
    # and close with a parenthesis
)
source=(
    # Insert URLs to the source(s) of your code here, usually one or more tar files
    # or such, like this:
    #     "source=("http://downloads.wordpress.org/plugin/$pars->{name}.\${pkgver}.zip")
)
sha512sums=(
    # List the checksums for one source at a time, same sequence as the in
    # the sources array, like this:
    #     '1c1e59d3733d4c1073c19f54c8eda48f71a7f9e8db74db7ab761fcd950445f7541bce5d9ac800238ab7099ff760cb51bd59b7426020128873fa166870c58f125'
)

package() {
# Manifest
    mkdir -p \${pkgdir}/var/lib/ubos/manifests
    install -m0644 \${startdir}/ubos-manifest.json \${pkgdir}/var/lib/ubos/manifests/\${pkgname}.json

# Icons
    mkdir -p \${pkgdir}/srv/http/_appicons/\${pkgname}
    install -m644 \${startdir}/appicons/{72x72,144x144}.png \${pkgdir}/srv/http/_appicons/\${pkgname}/

# Source
    mkdir -p \${pkgdir}/usr/share/\${pkgname}

    cp -a \${startdir}/src/$pars->{name} \${pkgdir}/usr/share/$pars->{name}/
}
END

    my $manifest = <<END;
{
    "type"  : "accessory",

    "accessoryinfo" : {
        "appid"         : "wordpress",
        "accessoryid"   : "$pars->{name}",
        "accessorytype" : "plugin"
    },

    "roles" : {
        "apache2" : {
            "appconfigitems" : [
                {
                    "type"   : "directorytree",
                    "name"   : "wp-content/plugins/$pars->{name}",
                    "source" : "$pars->{name}",
                }
            ],
            "installers" : [
                {
                    "type"   : "perlscript",
                    "source" : "/usr/share/wordpress/bin/activate-plugin.pl"
                }
            ]
        }
    }
}
END

    UBOS::Utils::mkdir( "$dir/appicons" );

    UBOS::Utils::saveFile( "$dir/PKGBUILD",           $pkgBuild,     0644 );
    UBOS::Utils::saveFile( "$dir/ubos-manifest.json", $manifest,     0644 );
}

##
# Return help text.
# return: help text
sub help {
    return 'Wordpress plugin';
}

1;
