#!/usr/bin/env bash

# Copyright 2006-2009 Amazon.com, Inc. or its affiliates.  All Rights Reserved.  Licensed under the 
# Amazon Software License (the "License").  You may not use this file except in compliance with the License. A copy of the 
# License is located at http://aws.amazon.com/asl or in the "license" file accompanying this file.  This file is distributed on an "AS 
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific 
# language governing permissions and limitations under the License.

# This script "concentrates" all of our Java invocations into a single location
# for maintainability.

# Simplified for UBOS (C) 2015 by Indie Computing Corp.

# 'Globals'
LIBDIR="/usr/share/ec2-api-tools/lib"

# If a classpath exists preserve it
CP="${CLASSPATH}"

CMD=$1
shift

for jar in "${LIBDIR}"/*.jar ; do
        CP="${CP}:${jar}"
done

/usr/bin/java ${EC2_JVM_ARGS} -classpath "${CP}" "com.amazon.aes.webservices.client.cmd.${CMD}" $EC2_DEFAULT_ARGS "$@"
